/// <reference path="./assets.d.ts" />
/** Texture URLs (bundled by Vite). Generated by scripts/build-living.mjs. */

import coral from "./assets/coral.webp";
import coralClean from "./assets/coral-clean.webp";
import coralEyes from "./assets/coral-eyes.png";
import coralMask from "./assets/coral-mask.png";
import lagoon from "./assets/lagoon.webp";
import lagoonClean from "./assets/lagoon-clean.webp";
import lagoonEyes from "./assets/lagoon-eyes.png";
import lagoonMask from "./assets/lagoon-mask.png";
import violet from "./assets/violet.webp";
import violetClean from "./assets/violet-clean.webp";
import violetEyes from "./assets/violet-eyes.png";
import violetMask from "./assets/violet-mask.png";
import type { LivingCharacterId } from "./characters";

export interface LivingTextures {
  color: string;
  clean: string;
  mask: string;
  eyes: string;
}

export const LIVING_TEXTURES: Record<LivingCharacterId, LivingTextures> = {
  violet: { color: violet, clean: violetClean, mask: violetMask, eyes: violetEyes },
  lagoon: { color: lagoon, clean: lagoonClean, mask: lagoonMask, eyes: lagoonEyes },
  coral: { color: coral, clean: coralClean, mask: coralMask, eyes: coralEyes },
};
