/** Generated by scripts/build-living.mjs — texture size, outline box, bottom anchor and eye boxes (px). */
export interface LivingMeta {
  w: number;
  h: number;
  /** Outline box of the whole character: x0, y0, x1, y1. */
  box: [number, number, number, number];
  /** Bottom centre of the body (where it rests on the ground). */
  anchor: [number, number];
  /** Eyes: centre x, centre y, width, height. */
  eyes: [number, number, number, number][];
}

export const LIVING_META: Record<"violet" | "lagoon" | "coral", LivingMeta> = {
  violet: {
    w: 512,
    h: 512,
    box: [38, 50, 477, 439],
    anchor: [274.8, 437],
    eyes: [
      [158.1, 232.4, 32, 57],
      [276.6, 258.7, 33, 57],
    ],
  },
  lagoon: {
    w: 512,
    h: 468,
    box: [75, 39, 446, 422],
    anchor: [226.9, 414],
    eyes: [
      [185.6, 142.7, 32, 57],
      [279, 162.9, 36, 60],
    ],
  },
  coral: {
    w: 512,
    h: 427,
    box: [71, 38, 440, 363],
    anchor: [276.5, 362],
    eyes: [
      [187.8, 194, 23, 44],
      [282.6, 205.9, 24, 45],
    ],
  },
};
