/**
 * Builds the "living" avatar textures from the cut-out concept renders (01-violet-cut.png, 02-lagoon-cut.png,
 * 03-coral-cut.png). The renders aren't in the repo; pass the folder that has them:
 *
 *   node packages/avatar/scripts/build-living.mjs <folder with the renders>
 *
 * For each character it writes to packages/avatar/src/living/assets/:
 *   <id>.webp        the render (RGBA, 512 px on the long side)
 *   <id>-clean.webp  the same render with the eyes removed (skin rebuilt), for blinks / "?" / moving eyes
 *   <id>-mask.png    R = headset, G = body
 *   <id>-eyes.png    R = eye region, G = eye matte (what counts as "eye", incl. its glossy rim)
 * and packages/avatar/src/living/meta.ts (texture size, outline box, bottom anchor, eye boxes).
 * Needs Playwright (already a dev dependency for the e2e suite).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = process.argv[2];
if (!SRC) {
  console.error("Usage: node packages/avatar/scripts/build-living.mjs <folder with the cut-out renders>");
  process.exit(2);
}
const OUT = join(here, "../src/living/assets");
const SIZE = 512;
const CHARACTERS = [
  { id: "violet", file: "01-violet-cut.png", bodyHue: 268 },
  { id: "lagoon", file: "02-lagoon-cut.png", bodyHue: 182 },
  { id: "coral", file: "03-coral-cut.png", bodyHue: 356 },
];

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent("<!doctype html><body></body>");
await page.addScriptTag({ content: readFileSync(join(here, "living-analyze.js"), "utf8") });

const meta = {};
for (const ch of CHARACTERS) {
  const src = `data:image/png;base64,${readFileSync(join(SRC, ch.file)).toString("base64")}`;
  const out = await page.evaluate(
    async ({ src, bodyHue, SIZE }) => {
      const im = new Image();
      im.src = src;
      await im.decode();
      const k = SIZE / Math.max(im.width, im.height);
      const c = document.createElement("canvas");
      c.width = Math.round(im.width * k);
      c.height = Math.round(im.height * k);
      const g = c.getContext("2d");
      g.imageSmoothingQuality = "high";
      g.drawImage(im, 0, 0, c.width, c.height);
      const small = c.toDataURL("image/png");
      const info = await analyze(small, bodyHue); // eslint-disable-line no-undef
      const opaque = (canvas) => {
        const o = document.createElement("canvas");
        o.width = canvas.width;
        o.height = canvas.height;
        const og = o.getContext("2d");
        og.fillStyle = "#000";
        og.fillRect(0, 0, o.width, o.height);
        og.drawImage(canvas, 0, 0);
        return o;
      };
      // Clean skin: only RGB matters (alpha comes from the render), so store it opaque to keep colours exact.
      const cleanSrc = info.clean.getContext("2d").getImageData(0, 0, info.W, info.H);
      for (let i = 3; i < cleanSrc.data.length; i += 4) cleanSrc.data[i] = 255;
      const clean = document.createElement("canvas");
      clean.width = info.W;
      clean.height = info.H;
      clean.getContext("2d").putImageData(cleanSrc, 0, 0);
      return {
        color: c.toDataURL("image/webp", 0.92),
        clean: clean.toDataURL("image/webp", 0.9),
        mask: opaque(info.mask).toDataURL("image/png"),
        eyes: opaque(info.eyeTex).toDataURL("image/png"),
        meta: { w: info.W, h: info.H, box: info.box, anchor: info.anchor, eyes: info.eyes },
      };
    },
    { src, bodyHue: ch.bodyHue, SIZE },
  );
  const save = (name, dataUrl) =>
    writeFileSync(join(OUT, name), Buffer.from(dataUrl.split(",")[1], "base64"));
  save(`${ch.id}.webp`, out.color);
  save(`${ch.id}-clean.webp`, out.clean);
  save(`${ch.id}-mask.png`, out.mask);
  save(`${ch.id}-eyes.png`, out.eyes);
  const r = (v) => Math.round(v * 10) / 10;
  meta[ch.id] = {
    w: out.meta.w,
    h: out.meta.h,
    box: out.meta.box,
    anchor: out.meta.anchor.map(r),
    eyes: out.meta.eyes.map((e) => e.map(r)),
  };
  console.log(ch.id, JSON.stringify(meta[ch.id]));
}
await browser.close();

writeFileSync(
  join(here, "../src/living/meta.ts"),
  `/** Generated by scripts/build-living.mjs — texture size, outline box, bottom anchor and eye boxes (px). */
export interface LivingMeta {
  w: number;
  h: number;
  /** Outline box of the whole character: x0, y0, x1, y1. */
  box: [number, number, number, number];
  /** Bottom centre of the body (where it rests on the ground). */
  anchor: [number, number];
  /** Eyes: centre x, centre y, width, height. */
  eyes: [number, number, number, number][];
}

export const LIVING_META: Record<"violet" | "lagoon" | "coral", LivingMeta> = ${JSON.stringify(meta, null, 2)};
`,
);
console.log("wrote meta.ts");
