import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { snapshotVersion } from "../../scripts/build-info.mjs";
import { resolveUpdateChannel } from "./scripts/channel.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");
// feed (owner) or github (public builds): see scripts/channel.mjs.
const update = resolveUpdateChannel(process.env, { publicSnapshot: snapshotVersion(repoRoot) !== null });

const common = {
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  sourcemap: true,
  external: ["electron", "bufferutil", "utf-8-validate"],
  define: {
    __YO_UPDATE_CHANNEL__: JSON.stringify(update.channel),
    __YO_UPDATE_REPO__: JSON.stringify(update.repo),
  },
};

await build({
  ...common,
  entryPoints: [path.join(here, "src/main.ts")],
  outfile: path.join(here, "dist/main.cjs"),
});
await build({
  ...common,
  entryPoints: [path.join(here, "src/preload.ts")],
  outfile: path.join(here, "dist/preload.cjs"),
});

// Where the agent's computer comes from: built from this checkout (repoRoot), or, for public builds that
// have no checkout, pulled as <computerImageRepo>:<app version> (main.ts adds the version).
fs.writeFileSync(
  path.join(here, "dist/yo-config.json"),
  JSON.stringify(
    update.computerImageRepo ? { computerImageRepo: update.computerImageRepo } : { repoRoot },
    null,
    2,
  ),
);

// electron-updater takes its cache folder name from this file (and needs it to exist). The feed URL in it is
// only a fallback: src/updates.ts sets the real one at runtime, on whatever port core uses.
fs.writeFileSync(
  path.join(here, "dist/app-update.yml"),
  "provider: generic\nurl: http://127.0.0.1:7777/api/updates/desktop\nupdaterCacheDirName: yo-updater\n",
);

// The "Starting Yo…" page main shows before it signs in (src/keychainWait.ts).
for (const f of ["starting.html", "logo.svg"])
  fs.copyFileSync(path.join(here, "static", f), path.join(here, "dist", f));

// Tray template icon (menu bar). Generated by packages/avatar/scripts if present.
for (const f of ["trayTemplate.png", "trayTemplate@2x.png"]) {
  const src = path.join(here, "build", f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(here, "dist", f));
}
console.log(
  `built desktop main + preload (updates: ${update.channel}${update.channel === "github" ? ` ${update.repo}` : ""})`,
);
